version: '3'

volumes:
  pg_data_production:
  frontend_static_volume:
  backend_static_volume:
  gateway_static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: vady8/taski_backend
    env_file: .env
    volumes:
      - backend_static_volume:/backend_static/static/
    depends_on:
      - db

  frontend:
    image: vady8/taski_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - frontend_static_volume:/frontend_static

  gateway:
    image: vady8/taski_gateway
    env_file: .env
    volumes:
      - gateway_static_volume:/staticfiles
    ports:
      - 8000:80

